### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by guguxh** [scotow/disrecord#1]
I did the download, but I don't want to run in docker, when I type the disrecord --discord-token TOKENHERE not happen. I'm using w10.

**Comment by scotow** [comment]
If you want to run `disrecord` manually, you will need the Rust toolchain installed (https://www.rust-lang.org/tools/install). And also the Opus codec (see `songbird`'s README for more info - https://github.com/serenity-rs/songbird#dependencies). And if you want to use different audio format and transcode it on the fly you will also need `ffmpeg` installed.

**Comment by guguxh** [comment]
I get a error when tried to build.

error: failed to run custom build command for `audiopus_sys v0.2.2`

Caused by:
  process didn't exit successfully: `C:\Users\GUILHERME\Desktop\terraria\gta\Discord\DISCORD UTILS\disrecord\target\debug\build\audiopus_sys-7e08cd38b26da00e\build-script-build` (exit code: 101)
  --- stdout
  cargo:info=No feature or environment variable found, linking by default.
  cargo:info=Opus source path used: "\\\\?\\C:\\Users\\GUILHERME\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\audiopus_sys-0.2.2\\opus".
  cargo:info=Building Opus via CMake.
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\GUILHERME\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\audiopus_sys-0.2.2\\opus" "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\GUILHERME\\Desktop\\terraria\\gta\\Discord\\DISCORD UTILS\\disrecord\\target\\debug\\build\\audiopus_sys-e697dfb8cdff3d29\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  thread 'main' panicked at '
  failed to execute command: program not found
  is `cmake` not installed?

  build script failed, must exit now', C:\Users\GUILHERME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by scotow** [comment]
You are missing some dependencies like `cmake` and probably others. This project uses `songbird` and those errors come from this lib or maybe lower libs (`audiopus_sys`). I'm not able to help you setup your Windows dev environment. You can try to build their example https://github.com/serenity-rs/songbird/tree/current/examples/serenity/voice, and ask them if they are willing to help you setup your environment if you don't succeed. You may also check their Discord server for help.
This is one reason why Docker images exist, so you don't have to setup a full environment if you don't know how to.
