### ISSUE TITLE
trying to run docker

### ISSUE THREAD

**Issue by jusplainmike** [scotow/disrecord#3]
I get this error when I try running the docker command.

```docker: Error response from daemon: source /var/lib/docker/overlay2/3b9398d0c8d31b1c0482c66019ccf803a7d3375b8f063ad9c2a640db27ab7d78/merged/disrecord is not directory.```

**Comment by scotow** [comment]
What docker command do you try to run?

Just tried to run the following command and didn't get any related error:
```
$ docker run --rm -it ghcr.io/scotow/disrecord/disrecord:0.3.3 --discord-token 123
[2024-03-27T11:13:51Z ERROR disrecord] bot starting error: 401: Unauthorized
```

**Comment by scotow** [comment]
I found the issue, the `docker run` example in the README tries to bind a volume on `/disrecord` which already exists and is the main binary. I will update the README to fix the example.

**Comment by jusplainmike** [comment]
Thank you. Yes that was the command I am running. Sorry at work will mark
it fixed after I test.
